---
title: "Modelo Multinomial Logit – Cali"
author: "Daniela Valdés"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: false
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

# ---- Paquetes ----

```{r}
library(readxl)
library(dplyr)
library(stringr)
library(janitor)
library(nnet)
library(forcats)
library(broom)
library(modelsummary)
```

# ---- Directorio de trabajo ----
```{r}
setwd("C:/Users/danie/OneDrive/Escritorio/Natura/201025_Results_Cali/")
```

# ---- 1) Cargar base y seleccionar variables ----

```{r}
path_input <- "C:/Users/danie/OneDrive/Escritorio/Natura/201025_Results_Cali/|output/input_famd_cali_29102025.xlsx"
df <- read_excel(path_input) %>% janitor::clean_names()
```

# Variables independientes

```{r}
vars_x <- c(
"edad_r2","p5_agregado","p9_estrato3","p40",
"p28_importancia_costo_compra","p28_importancia_costo_uso","p28_importancia_comodidad",
"p28_importancia_tiempo","p28_importancia_emisiones","p28_importancia_siniestralidad",
"p32_contaminacion_likert","p36_influencia_amigos","p37_influencia_familia","tiempo_total"
)
```

```{r}
vars_keep  <- c("medio", vars_x)
vars_exist <- vars_keep[vars_keep %in% names(df)]
df <- df[, vars_exist, drop = FALSE]
```

# ---- 2) Tipos: categóricas y numéricas ----

```{r}
cat_vars <- intersect(c("edad_r2","p5_agregado","p9_estrato3","p40"), names(df))
num_vars <- setdiff(intersect(vars_x, names(df)), cat_vars)

df <- df %>%
mutate(
across(all_of(cat_vars), ~ droplevels(as.factor(.))),
across(all_of(num_vars), ~ suppressWarnings(as.numeric(.))),
medio = droplevels(as.factor(medio))
)
```

# ---- 3) Modelo multinomial ----

```{r}
x_in_formula <- paste(intersect(vars_x, names(df)), collapse = " + ")
f_full <- as.formula(paste0("medio ~ ", x_in_formula))

m_full <- nnet::multinom(f_full, data = df, Hess = TRUE, trace = FALSE, maxit = 1000)
```

# ---- 4) Mostrar resultados en HTML ----
```{r}
modelsummary(
list("Modelo Multinomial – Cali" = m_full),
exponentiate = TRUE,
conf_level   = 0.95,
estimate     = "{estimate} [{conf.low}, {conf.high}]",
statistic    = "p = {p.value}",
gof_omit     = "AIC|BIC|Log.Lik|Adj|Pseudo|RMSE|IC|R2",
shape        = term ~ y.level
)
```