---
title: "Modelo Multinomial Logit – Cali"
author: "Daniela Valdés"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: false
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(dplyr)
library(nnet)
library(readxl)
library(tidyverse)
library(ggplot2)
library(GGally)
library(stargazer)
library(writexl)
```

# Ruta
```{r}
dataset <- read_excel("C:\\Users\\danie\\OneDrive\\Escritorio\\Natura\\201025_Results_Cali\\output\\input_famd_cali_29102025.xlsx")
```

# Ajuste de variables
```{r}
## Modificacion base con dummies 
columna_dummy <- function(df, columna) {
  df %>% 
    mutate_at(columna, ~paste(columna, eval(as.symbol(columna)), sep = "_")) %>% 
    mutate(valor = 1) %>% 
    spread(key = columna, value = valor, fill = 0)
}

# Eliminar categorías de genero
dataset <- subset(dataset, !(p40 %in% c("Otro", "Prefiere no responder", "Otras identidades de género")))

# Conversion de variables categoricas 
dataset <- columna_dummy(dataset, "edad_r2")
dataset <- columna_dummy(dataset, "p5_agregado")
dataset <- columna_dummy(dataset, "p9_estrato3")
dataset <- columna_dummy(dataset, "p40")
dataset <- columna_dummy(dataset, "p7_agregado")
dataset <- columna_dummy(dataset, "p22")

dataset <- subset(dataset, select = -id)
```

# Modelo: Logit Multinomial
```{r}
dataset$medio <- factor(dataset$medio)

# p22_Más de 12 km
# Hombre
# edad_r2_35 - 54 años
#`p5_agregado_Superior`
#`p9_estrato3_Alto`
#`p7_agregado_Ocupado/a`

modelo_multinomial <- multinom(
  medio ~ p28_importancia_costo_compra + 
    p28_importancia_costo_uso + p28_importancia_comodidad + 
    p28_importancia_tiempo + p28_importancia_emisiones +
    p28_importancia_siniestralidad + 
    p32_contaminacion_likert + p36_influencia_amigos +
    p37_influencia_familia + tiempo_total +
    `p22_Menos de 1 km`  + 
    `p22_Entre 8 y 12 km` + `p22_Entre 4 y 7 km` + 
    `p22_Entre 1 y 3 km` + `p7_agregado_Trabajo doméstico no remunerado` +
    `p7_agregado_Otro` + 
    `p7_agregado_Estudiante` + `p7_agregado_Desocupado o inactivo` + 
    `p40_Mujer` + `edad_r2_18 - 34 años` + 
    `edad_r2_55 - 80 años` + 
    `p5_agregado_Primaria o menos` + `p5_agregado_Secundaria` + 
    `p5_agregado_Sin respuesta` + 
    `p5_agregado_Técnico / Tecnológico` +
    `p9_estrato3_Bajo` + p9_estrato3_Medio,
  data = dataset
)
```

## Resultados
```{r}
# Tabla de resultados
stargazer(
  modelo_multinomial,
  type = "text",
  title = "Resultados del Modelo Logit Multinomial",
  single.row = TRUE
)
```